@startuml
digraph dfd{
	node[shape=record]

uasp_streaming_mdm_enrichment_way4 [label="{<f0> uasp_streaming_mdm_enrichment_way4 |<f1> uasp_streaming_mdm_enrichment_way4\n\n\n}" shape=Mrecord];
dev_ivr__uasp_realtime__input_converter__mortgage__dlq [label="dev_ivr__uasp_realtime__input_converter__mortgage__dlq" shape=box color=Green];
dev_ivr__uasp_realtime__mdm_enrichment__for_additional_enrichment__uaspdto [label="dev_ivr__uasp_realtime__mdm_enrichment__for_additional_enrichment__uaspdto" shape=box color=Green];
dev_ivr__uasp_realtime__mdm_enrichment__mdm_cross_link__status__dlq [label="dev_ivr__uasp_realtime__mdm_enrichment__mdm_cross_link__status__dlq" shape=box color=Green];
dev_ivr__uasp_realtime_way4_mdm_enrichment__uaspdto [label="dev_ivr__uasp_realtime_way4_mdm_enrichment__uaspdto" shape=box color=Green];
uasp_streaming_mdm_enrichment_way4_card_agreement [label="{<f0> uasp_streaming_mdm_enrichment_way4_card_agreement |<f1> uasp_streaming_mdm_enrichment_way4_card_agreement\n\n\n}" shape=Mrecord];
dev_bevents_card_agreement_enrich_out_uaspdto [label="dev_bevents_card_agreement_enrich_out_uaspdto" shape=box color=Green];
dev_bevents_card_agreement_enrich_way4_dlq [label="dev_bevents_card_agreement_enrich_way4_dlq" shape=box color=Green];
dev_rto_batch_ca_customer_card_uaspdto__dlq [label="dev_rto_batch_ca_customer_card_uaspdto__dlq" shape=box color=Green];
dev__dko_uasp__card_agreement_converted [label="dev__dko_uasp__card_agreement_converted" shape=box color=Green];
dev_ivr__uasp_realtime__case_48_concatenate__uaspdto [label="dev_ivr__uasp_realtime__case_48_concatenate__uaspdto" shape=box color=Green];
dev_ivr__uasp_realtime__input_converter__mdm_cross_link__uaspdto [label="dev_ivr__uasp_realtime__input_converter__mdm_cross_link__uaspdto" shape=box color=Green];
dev_ivr__uasp_realtime__input_converter__mortgage__uaspdto [label="dev_ivr__uasp_realtime__input_converter__mortgage__uaspdto" shape=box color=Green];
dev_ivr__uasp_realtime__input_converter__way4_issuing_operation__uaspdto [label="dev_ivr__uasp_realtime__input_converter__way4_issuing_operation__uaspdto" shape=box color=Green];

uasp_streaming_mdm_enrichment_way4 -> dev_ivr__uasp_realtime__input_converter__mortgage__dlq
uasp_streaming_mdm_enrichment_way4 -> dev_ivr__uasp_realtime__mdm_enrichment__for_additional_enrichment__uaspdto
uasp_streaming_mdm_enrichment_way4 -> dev_ivr__uasp_realtime__mdm_enrichment__mdm_cross_link__status__dlq
uasp_streaming_mdm_enrichment_way4 -> dev_ivr__uasp_realtime_way4_mdm_enrichment__uaspdto
uasp_streaming_mdm_enrichment_way4_card_agreement -> dev_bevents_card_agreement_enrich_out_uaspdto
uasp_streaming_mdm_enrichment_way4_card_agreement -> dev_bevents_card_agreement_enrich_way4_dlq
uasp_streaming_mdm_enrichment_way4_card_agreement -> dev_rto_batch_ca_customer_card_uaspdto__dlq
dev__dko_uasp__card_agreement_converted -> uasp_streaming_mdm_enrichment_way4_card_agreement
dev_ivr__uasp_realtime__case_48_concatenate__uaspdto -> uasp_streaming_mdm_enrichment_way4_card_agreement
dev_ivr__uasp_realtime__input_converter__mdm_cross_link__uaspdto -> uasp_streaming_mdm_enrichment_way4
dev_ivr__uasp_realtime__input_converter__mortgage__uaspdto -> uasp_streaming_mdm_enrichment_way4
dev_ivr__uasp_realtime__input_converter__way4_issuing_operation__uaspdto -> uasp_streaming_mdm_enrichment_way4

}
@enduml