package ru.vtb.uasp.validate;

global org.slf4j.Logger logger

import scala.Some
import ru.vtb.uasp.common.dto.UaspDto
import ru.vtb.uasp.validate.entity.ValidateMsg
import ru.vtb.uasp.mutator.configuration.drools.DrlHelper
import java.util.Arrays
import java.math.*
import ru.vtb.bevent.first.salary.aggregate.Util.DrlCaseHelper


import ru.vtb.uasp.mutator.service.dto.*

dialect "mvel"

rule "case 8"
when
    UaspDto($cid:dataString.get("account_number_prf"), DrlHelper.isNonEmpty($cid))
    and
    UaspDto($isProfile:dataBoolean.get("is_withdraw_profile"), DrlHelper.isNonEmpty($isProfile) && $isProfile.get==true )
    and
    UaspDto($drcr_prf:dataString.get("drcr_prf"), DrlHelper.isNonEmpty($drcr_prf) && $drcr_prf.get=="DR")
    and
    UaspDto($spr:dataString.get("spr_prf"), DrlHelper.isNonEmpty($spr))
    and
    UaspDto($endBalRur:dataDecimal.get("BALANCE_RUR"), DrlHelper.isNonEmpty($endBalRur))
    and
    UaspDto($amount:dataDecimal.get("amount"), DrlHelper.isNonEmpty($amount) && DrlCaseHelper.isCase8($amount.get.toString, $endBalRur.get.toString))

then

    insert(new UaspOperation(drools.getRule().getName(), new StringMap("Profile." + $cid.get + "."+ $spr.get), "OPERATION_ID", new Add()))
    insert(new UaspOperation(drools.getRule().getName(), new StringMap("Успешно"), "OPERATION_STATUS", new Add()))
    insert(new UaspOperation(drools.getRule().getName(), new StringMap("MASTER_ACCOUNT"), "ACCOUNT_NM", new Add()))

    insert(new UaspOperation(drools.getRule().getName(), new StringMap("RTO_8_case"), "system-classification", new Add()))

end
