package ru.vtb.uasp.validate;

global org.slf4j.Logger logger

import scala.Some
import ru.vtb.uasp.common.dto.UaspDto
import ru.vtb.uasp.validate.entity.ValidateMsg
import ru.vtb.uasp.mutator.configuration.drools.DrlHelper
import java.util.Arrays

import ru.vtb.uasp.mutator.service.dto.*

dialect "mvel"

rule "ns count < 3"
when

    UaspDto($isNS:dataBoolean.get("is_ns"), DrlHelper.isNonEmpty($isNS) && $isNS.get==true )
    and
    UaspDto($count:dataInt.get("COUNT_REP"), DrlHelper.isNonEmpty($count) && $count.get<=2)

then
    insert(new UaspOperation(drools.getRule().getName(), new StringMap("RTO_First_NS_38_case"), "system-classification", new Add()))
    insert(new UaspOperation(drools.getRule().getName(), new IntMap($count.get+1), "EVENT_CNT", new Add()))
    insert(new UaspOperation(drools.getRule().getName(), new BooleanMap(true), "system_is_update_ns", new Add()))

end

