package ru.vtb.uasp.validate;

global org.slf4j.Logger logger

import scala.Some
import ru.vtb.uasp.common.dto.UaspDto
import ru.vtb.uasp.validate.entity.ValidateMsg
import ru.vtb.uasp.mutator.configuration.drools.DrlHelper
import java.util.Arrays

import ru.vtb.uasp.mutator.service.dto.*

dialect "mvel"

rule "Source account fields name unification from CFT pipeline"
salience 10
when
    UaspDto($sourceAccount:dataString.get("source_account_cft"), DrlHelper.isNonEmpty($sourceAccount))

then
    String sourceAccount = $sourceAccount.get

    insert(new UaspOperation(drools.getRule().getName(), new StringMap(sourceAccount), "source_account", new Add()))
end


rule "Source account fields name unification from CA pipeline"
salience 10
when
    UaspDto($sourceAccount:dataString.get("source_account_ca"), DrlHelper.isNonEmpty($sourceAccount))

then
    String sourceAccount = $sourceAccount.get

    insert(new UaspOperation(drools.getRule().getName(), new StringMap(sourceAccount), "source_account", new Add()))
end


rule "Source account fields name unification from Profile pipeline"
salience 10
when
    UaspDto($sourceAccount:dataString.get("contract_num"), DrlHelper.isNonEmpty($sourceAccount))
then
    String sourceAccount = $sourceAccount.get

    insert(new UaspOperation(drools.getRule().getName(), new StringMap(sourceAccount), "source_account", new Add()))
end


rule "Source account fields name unification from W4 pipeline"
salience 10
when
    UaspDto($sourceAccount:dataString.get("source_account_w4"), DrlHelper.isNonEmpty($sourceAccount))

then
    String sourceAccount = $sourceAccount.get

    insert(new UaspOperation(drools.getRule().getName(), new StringMap(sourceAccount), "source_account", new Add()))
end


rule "Source account fields name unification from withdraw pipeline"
salience 10
when
    UaspDto($sourceAccount:dataString.get("sourceAccount"), DrlHelper.isNonEmpty($sourceAccount))

then
    String sourceAccount = $sourceAccount.get

    insert(new UaspOperation(drools.getRule().getName(), new StringMap(sourceAccount), "source_account", new Add()))
end
