bussines.rulles.flink.job.checkpoint.sync.parallelism=8

bussines.rulles.kafka.consumer.property.auto.offset.reset=latest

bussines.rulles.kafka.consumer.property.check.crcs=true
bussines.rulles.kafka.consumer.property.connections.max.idle.ms=540000
bussines.rulles.kafka.consumer.property.enable.auto.commit=true

bussines.rulles.kafka.consumer.property.fetch.max.bytes=52428800
bussines.rulles.kafka.consumer.property.fetch.max.wait.ms=500
bussines.rulles.kafka.consumer.property.fetch.min.bytes=50

bussines.rulles.kafka.consumer.property.heartbeat.interval.ms=3000
bussines.rulles.kafka.consumer.property.max.partition.fetch.bytes=1048576
bussines.rulles.kafka.consumer.property.max.poll.interval.ms=300000
bussines.rulles.kafka.consumer.property.max.poll.records=500
bussines.rulles.kafka.consumer.property.metadata.max.age.ms=300000
bussines.rulles.kafka.consumer.property.metrics.num.samples=2

bussines.rulles.kafka.producer.transaction.timeout.ms=1800000