package ru.vtb.uasp.validate;

global org.slf4j.Logger logger

import scala.Some
import ru.vtb.uasp.common.dto.UaspDto
import ru.vtb.uasp.validate.entity.ValidateMsg
import ru.vtb.uasp.mutator.configuration.drools.DrlHelper
import java.util.Arrays
import ru.vtb.uasp.mutator.service.dto.*

dialect "mvel"

rule "NS-rule"
  when
    UaspDto($actionType:dataBoolean.get("first_add_cft"), $actionType.nonEmpty)
  then
    insert(new UaspOperation(drools.getRule().getName(), new StringMap("way4-case-NS"), "system-uasp-way-classification", new ConcatenateStr(",")))
end