package ru.vtb.uasp.validate;

global org.slf4j.Logger logger

import scala.Some
import ru.vtb.uasp.common.dto.UaspDto
import ru.vtb.uasp.validate.entity.ValidateMsg
import ru.vtb.uasp.mutator.configuration.drools.DrlHelper

import ru.vtb.uasp.mutator.service.dto.*

dialect "mvel"

rule "2.3"
  when
    UaspDto($operationId:dataString.get("operation_id"), DrlHelper.isNonEmpty($operationId))
    and
    UaspDto($localId:dataString.get("local_id"), DrlHelper.isNonEmpty($localId))
    and
    UaspDto($auditRefSrn:dataString.get("audit_srn"), DrlHelper.isNonEmpty($auditRefSrn))
    and
    UaspDto($transactionDatetime:dataLong.get("transaction_datetime"), DrlHelper.isNonEmpty($transactionDatetime))
    and
    UaspDto($effectiveDate:dataLong.get("effective_date"), DrlHelper.isNonEmpty($effectiveDate))
    and
    (
        (   UaspDto($actionType:dataString.get("action_type"), $actionType.nonEmpty && $actionType.get == "AuthorizationReversal")
            and
            UaspDto($processingResolution:dataString.get("processing_resolution"), $processingResolution.nonEmpty && $processingResolution.get == "Accepted")
        )
        or
        (
            UaspDto($actionType:dataString.get("action_type"), $actionType.nonEmpty && $actionType.get == "PresentmentReversal")
            and
            UaspDto($processingResolution:dataString.get("processing_resolution"), $processingResolution.nonEmpty && $processingResolution.get == "Accepted")
         )
        or
        (
            UaspDto($actionType:dataString.get("action_type"), $actionType.nonEmpty && $actionType.get == "Presentment")
            and
            UaspDto($processingResolution:dataString.get("processing_resolution"), $processingResolution.nonEmpty && $processingResolution.get == "Rejected"))
    )
    and
    UaspDto($auditRefAuthcode:dataString.get("audit_auth_code"), DrlHelper.isNonEmpty($auditRefAuthcode))
    and
    UaspDto($auditRefRrn:dataString.get("audit_rrn"), DrlHelper.isNonEmpty($auditRefRrn))
  then
    insert(new UaspOperation(drools.getRule().getName(), new StringMap("way4-case-2-3"), "system-uasp-way-classification", new ConcatenateStr(",")))
end