package ru.vtb.uasp.validate;

global org.slf4j.Logger logger

import scala.Some
import ru.vtb.uasp.common.dto.UaspDto
import ru.vtb.uasp.validate.entity.ValidateMsg
import ru.vtb.uasp.mutator.configuration.drools.DrlHelper
import ru.vtb.uasp.mutator.service.dto.UaspOperation
import ru.vtb.uasp.mutator.service.dto.IntMap
import ru.vtb.uasp.mutator.service.dto.Mutate

dialect "mvel"

rule "test_2"
  when
    UaspDto($localId:dataInt.get("someInt"), !DrlHelper.isEven($localId))
  then
    insert(new UaspOperation(drools.getRule().getName(), new IntMap($localId.get() * 10), "someInt", new Delete()))
    insert(new UaspOperation(drools.getRule().getName(), new IntMap($localId.get() + 0), "someInt1", new Add()))
end