package ru.vtb.uasp.validate;

global org.slf4j.Logger logger

import scala.Some
import ru.vtb.uasp.common.dto.UaspDto
import ru.vtb.uasp.validate.entity.ValidateMsg
import ru.vtb.uasp.mutator.configuration.drools.DrlHelper

import ru.vtb.uasp.mutator.service.dto.*

dialect "mvel"

rule "48"
  when

    UaspDto($customerId:dataString.get("local_id"), DrlHelper.isNonEmpty($customerId))
    UaspDto($maskedCardNumber:dataString.get("card_masked_pan"), DrlHelper.isNonEmpty($maskedCardNumber))
  then
    String m = $maskedCardNumber.get
    String c = $customerId.get

    insert(new UaspOperation(drools.getRule().getName(), new StringMap(c +";" + m), "customer_id_and_masked_card_number", new Add()))
end