package ru.vtb.uasp.validate;

global org.slf4j.Logger logger

import scala.Some
import ru.vtb.uasp.common.dto.UaspDto
import ru.vtb.uasp.validate.entity.ValidateMsg
import ru.vtb.uasp.mutator.configuration.drools.DrlHelper
import ru.vtb.uasp.mutator.service.dto.*

dialect "mvel"


rule "2.9"
  when
    UaspDto($localId:dataString.get("local_id"), DrlHelper.isNonEmpty($localId))
    UaspDto($actionType:dataString.get("action_type"), DrlHelper.isNonEmpty($actionType))
    UaspDto($chainServiceType:dataString.get("service_type"), $chainServiceType.nonEmpty)
    UaspDto($transactionAmount:dataDecimal.get("transaction_amount"), DrlHelper.isNonEmpty($transactionAmount))
    UaspDto($baseTransactionAmount:dataDecimal.get("base_transaction_amount"), DrlHelper.isNonEmpty($baseTransactionAmount))
    UaspDto($feeAmount:dataDecimal.get("fee_amount"), DrlHelper.isNonEmpty($feeAmount))
    UaspDto($psFundingSource:dataDecimal.get("ps_funding_source"), DrlHelper.isNonEmpty($psFundingSource))



  then
    insert(new UaspOperation(drools.getRule().getName(), new StringMap("way4-case-2-9"), "system-uasp-way-classification", new ConcatenateStr(",")))
end