package ru.vtb.uasp.validate;

global org.slf4j.Logger logger

import scala.Some
import ru.vtb.uasp.common.dto.UaspDto
import ru.vtb.uasp.validate.entity.ValidateMsg
import ru.vtb.uasp.mutator.configuration.drools.DrlHelper
import java.util.Arrays
import ru.vtb.uasp.mutator.service.dto.*

dialect "mvel"

rule "11.2"
  when
    UaspDto($operationId:dataString.get("operation_id"), DrlHelper.isNonEmpty($operationId))
    UaspDto($localId:dataString.get("local_id"), DrlHelper.isNonEmpty($localId))
    UaspDto($transactionDatetime:dataLong.get("transaction_datetime"), DrlHelper.isNonEmpty($transactionDatetime))

    UaspDto($actionType:dataString.get("action_type"), $actionType.nonEmpty && $actionType.get == "Presentment")
    UaspDto($processingResolution:dataString.get("processing_resolution"), $processingResolution.nonEmpty && $processingResolution.get == "Accepted")
    UaspDto($requestedAmountPaymentDirection:dataString.get("payment_direction"), $requestedAmountPaymentDirection.nonEmpty && $requestedAmountPaymentDirection.get == "Credit")
    UaspDto($isHypotec:dataBoolean.get("is_mortgage"), $isHypotec.nonEmpty && $isHypotec.get == true)

  then
    insert(new UaspOperation(drools.getRule().getName(), new StringMap("way4-case-11-2"), "system-uasp-way-classification", new ConcatenateStr(",")))
end