package ru.vtb.uasp.validate;

global org.slf4j.Logger logger

import scala.Some
import ru.vtb.uasp.common.dto.UaspDto
import ru.vtb.uasp.validate.entity.ValidateMsg
import ru.vtb.uasp.mutator.configuration.drools.DrlHelper
import ru.vtb.uasp.mutator.service.dto.*

dialect "mvel"

rule "2.4"
  when
    UaspDto($operationId:dataString.get("operation_id"), DrlHelper.isNonEmpty($operationId))
    UaspDto($localId:dataString.get("local_id"), DrlHelper.isNonEmpty($localId))
    UaspDto($effectiveDate:dataLong.get("effective_date"), DrlHelper.isNonEmpty($effectiveDate))
    //
    UaspDto($actionType:dataString.get("action_type"), $actionType.nonEmpty && $actionType.get == "Presentment")
    UaspDto($auditRefAuthcode:dataString.get("audit_auth_code"), !DrlHelper.isNonEmpty($auditRefAuthcode)) // поле должно быть, но оно должно быть пустым
    UaspDto($auditRefRrn:dataString.get("audit_rrn"), !DrlHelper.isNonEmpty($auditRefRrn)) // поле должно быть, но оно должно быть пустым
    UaspDto($processingResolution:dataString.get("processing_resolution"), $processingResolution.nonEmpty && $processingResolution.get == "Accepted")
    UaspDto($paymentDirection:dataString.get("payment_direction"), $paymentDirection.nonEmpty && $paymentDirection.get == "Debit")
  then
    insert(new UaspOperation(drools.getRule().getName(), new StringMap("way4-case-2-4"), "system-uasp-way-classification", new ConcatenateStr(",")))
end