package ru.vtb.uasp.validate;

global org.slf4j.Logger logger

import scala.Some
import ru.vtb.uasp.common.dto.UaspDto
import ru.vtb.uasp.validate.entity.ValidateMsg
import ru.vtb.uasp.mutator.configuration.drools.DrlHelper
import ru.vtb.uasp.mutator.service.dto.*

dialect "mvel"

rule "2.7"
  when
  UaspDto($localId:dataString.get("local_id"), DrlHelper.isNonEmpty($localId))
  and
  UaspDto($actionType:dataString.get("action_type"), DrlHelper.isNonEmpty($actionType) && $actionType.get == "Presentment")
   and
  UaspDto($chainServiceType:dataString.get("service_type"), DrlHelper.isNonEmpty($chainServiceType) && $chainServiceType.get == "F7")
   and
  UaspDto($serviceDateTime:dataLong.get("service_datetime"), DrlHelper.isNonEmpty($serviceDateTime))
   and
  UaspDto($effectiveDate:dataLong.get("effective_date"), DrlHelper.isNonEmpty($effectiveDate))
   and
  UaspDto($processingResolution:dataString.get("processing_resolution"), DrlHelper.isNonEmpty($processingResolution) && $processingResolution.get == "Accepted")
     and
  UaspDto($feeAmount:dataDecimal.get("fee_amount"), DrlHelper.isNonEmpty($feeAmount))




  then
    insert(new UaspOperation(drools.getRule().getName(), new StringMap("way4-case-2-7"), "system-uasp-way-classification", new ConcatenateStr(",")))
end