package ru.vtb.uasp.validate;

global org.slf4j.Logger logger

import scala.Some
import ru.vtb.uasp.common.dto.UaspDto
import ru.vtb.uasp.mutator.configuration.drools.DrlHelper
import ru.vtb.uasp.mutator.service.dto.UaspOperation
import ru.vtb.uasp.mutator.service.dto.*

dialect "mvel"

rule "2.10"
  when
    UaspDto($operationId:dataString.get("operation_id"), DrlHelper.isNonEmpty($operationId))
    UaspDto($localId:dataString.get("local_id"), DrlHelper.isNonEmpty($localId))
    UaspDto($transactionAmount:dataDecimal.get("transaction_amount"), DrlHelper.isNonEmpty($transactionAmount))
    UaspDto($effectiveDate:dataLong.get("effective_date"), DrlHelper.isNonEmpty($effectiveDate))
    UaspDto($processingResolution:dataString.get("processing_resolution"), DrlHelper.isNonEmpty($processingResolution))
    //
    UaspDto($actionType:dataString.get("action_type"), $actionType.nonEmpty && $actionType.get == "Authorization")
    UaspDto($paymentDirection:dataString.get("payment_direction"), $paymentDirection.nonEmpty && $paymentDirection.get == "Debit") // Добавить поле
    UaspDto($processingResultCode:dataString.get("processing_result_code"), $processingResultCode.nonEmpty && DrlHelper.toIntGt($processingResultCode, 0))
  then
    insert(new UaspOperation(drools.getRule().getName(), new StringMap("way4-case-2-10"), "system-uasp-way-classification", new ConcatenateStr(",")))
end