package ru.vtb.uasp.validate;

global org.slf4j.Logger logger

import ru.vtb.uasp.common.dto.UaspDto
import ru.vtb.uasp.validate.entity.ValidateMsg
import ru.vtb.uasp.inputconvertor.utils.DrlHelper

dialect "mvel"

//
//// Идентификатор клиента должен быть обязательно
//rule "The client ID must be mandatory"
//  when
//    UaspDto(id.isEmpty)
//  then
//    insert(new ValidateMsg(drools.getRule().getName()))
//end
